import { UserStats, LeaderboardEntry, Prediction } from '../types/data';

export const mockUserStats: Record<string, UserStats> = {
  user1: {
    userId: 'user1',
    accuracy: 65.5,
    currentStreak: 3,
    longestStreak: 7,
    totalPoints: 1250,
    totalPredictions: 45,
    correctPredictions: 30,
    favoriteWeightClass: 'Lightweight',
    bestPerformingWeightClass: 'Welterweight',
    rank: 1,
    createdAt: new Date(Date.now() - 90 * 24 * 60 * 60 * 1000).toISOString(),
    lastLogin: new Date().toISOString(),
    lastThreePredictions: [
      {
        userId: 'user1',
        eventId: 'event1',
        fightId: 'fight1',
        selectedFighter: 'Islam Makhachev',
        confidence: 85,
        timestamp: new Date().toISOString(),
        isCorrect: true,
        points: 100,
      },
      {
        userId: 'user1',
        eventId: 'event2',
        fightId: 'fight2',
        selectedFighter: 'Leon Edwards',
        confidence: 75,
        timestamp: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
        isCorrect: true,
        points: 75,
      },
      {
        userId: 'user1',
        eventId: 'event3',
        fightId: 'fight3',
        selectedFighter: 'Sean O\'Malley',
        confidence: 60,
        timestamp: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
        isCorrect: false,
        points: 0,
      },
    ],
    biggestUpset: {
      eventId: 'event4',
      fightId: 'fight4',
      points: 175,
      odds: 350,
    },
  },
  user2: {
    userId: 'user2',
    accuracy: 58.2,
    currentStreak: 1,
    longestStreak: 4,
    totalPoints: 850,
    totalPredictions: 35,
    correctPredictions: 20,
    favoriteWeightClass: 'Heavyweight',
    bestPerformingWeightClass: 'Middleweight',
    rank: 3,
    createdAt: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(),
    lastLogin: new Date().toISOString(),
    lastThreePredictions: [
      {
        userId: 'user2',
        eventId: 'event1',
        fightId: 'fight4',
        selectedFighter: 'Tom Aspinall',
        confidence: 70,
        timestamp: new Date().toISOString(),
        isCorrect: true,
        points: 50,
      },
      {
        userId: 'user2',
        eventId: 'event2',
        fightId: 'fight5',
        selectedFighter: 'Israel Adesanya',
        confidence: 80,
        timestamp: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
        isCorrect: false,
        points: 0,
      },
      {
        userId: 'user2',
        eventId: 'event3',
        fightId: 'fight6',
        selectedFighter: 'Francis Ngannou',
        confidence: 65,
        timestamp: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
        isCorrect: true,
        points: 100,
      },
    ],
    biggestUpset: {
      eventId: 'event5',
      fightId: 'fight5',
      points: 125,
      odds: 250,
    },
  },
};

export const mockLeaderboard: LeaderboardEntry[] = [
  {
    userId: 'user1',
    username: 'Champ',
    totalPoints: 850,
    accuracy: 71.1,
    currentStreak: 5,
    longestStreak: 8,
    rank: 1,
    totalPredictions: 45,
    correctPredictions: 32
  },
  {
    userId: 'user2',
    username: 'Contender',
    totalPoints: 720,
    accuracy: 66.7,
    currentStreak: 3,
    longestStreak: 6,
    rank: 3,
    totalPredictions: 42,
    correctPredictions: 28
  },
  {
    userId: 'user3',
    username: 'Prospect',
    totalPoints: 650,
    accuracy: 65.8,
    currentStreak: 2,
    longestStreak: 5,
    rank: 5,
    totalPredictions: 38,
    correctPredictions: 25
  }
]; 